name: Deploy foetus.pdf

on:
  push:
    branches: [ master ]
    paths:
    - '.github/workflows/deploy.yml'
    - '*.tex'
    - 'Makefile'
    - 'html/index.html'
  pull_request:
    branches: [ master ]
    paths:
    - '.github/workflows/deploy.yml'
    - '*.tex'
    - 'Makefile'
    - 'html/index.html'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Install tectonic
      uses: wtfjoke/setup-tectonic@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # The GITHUB_TOKEN is needed to query the Github Releases of tectonic-typesetting/tectonic
        # to download tectonic.

    - name: Tectonic version
      run: |
        tectonic --version

    - uses: actions/checkout@v4

    - name: Run tectonic
      run: |
        tectonic -o html foetus.tex

    - uses: actions/upload-pages-artifact@v3
      with:
        path: html

  # Deploy job, see https://github.com/actions/deploy-pages/tree/f81ad71d2e78487340fb3a94726f2a6050466efd#readme
  deploy:
    if: github.ref == 'refs/heads/master'
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages:    write   # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:

    - name: Deploy to GitHub Pages
      id:   deployment
      uses: actions/deploy-pages@v4
